export const TIMER_START = 'TIMER_START';
export const TIMER_STOP = 'TIMER_STOP';
export const TIMER_TICK = 'TIMER_TICK';
export const TIMER_RESET = 'TIMER_RESET';

export const PREVIOUS_TIMER_DATA_LOADED = 'PREVIOUS_TIMER_DATA_LOADED';
export const READ_FROM_LOCAL_STORAGE = 'READ_FROM_LOCAL_STORAGE';
export const WRITE_TO_LOCAL_STORAGE = 'WRITE_TO_LOCAL_STORAGE';
